// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/mechanics/add": {
            "post": {
                "description": "Handles mechanic add request by validating input and storing mechanics details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mechanics"
                ],
                "summary": "Adds new mechanic",
                "parameters": [
                    {
                        "description": "mechanic add Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BFFAddMechanicRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "mechanic added successfully",
                        "schema": {
                            "$ref": "#/definitions/models.BFFAddMechanicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input payload",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "409": {
                        "description": "Duplicate value in request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    }
                }
            }
        },
        "/api/mechanics/delete": {
            "post": {
                "description": "Handles mechanic Delete request by validating input.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mechanics"
                ],
                "summary": "Delete mechanic",
                "parameters": [
                    {
                        "description": "mechanic Delete Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BFFDeleteMechanicRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mechanic Deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/models.BFFDeleteMechanicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input payload",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    }
                }
            }
        },
        "/api/services/add": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds a new service to the DB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "Add a new service",
                "parameters": [
                    {
                        "description": "Add Service Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BFFAddNewServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Added service successful",
                        "schema": {
                            "$ref": "#/definitions/models.BFFAddNewServiceResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input payload",
                        "schema": {
                            "$ref": "#/definitions/models.BFFAddNewServiceResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized role",
                        "schema": {
                            "$ref": "#/definitions/models.BFFAddNewServiceResponse"
                        }
                    },
                    "409": {
                        "description": "Service already exists",
                        "schema": {
                            "$ref": "#/definitions/models.BFFAddNewServiceResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BFFAddNewServiceResponse"
                        }
                    }
                }
            }
        },
        "/api/services/delete": {
            "delete": {
                "description": "Deletes an existing service from the DB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Services"
                ],
                "summary": "Delete an existing service",
                "parameters": [
                    {
                        "description": "Delete Service Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BFFDeleteServiceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deleted service successful",
                        "schema": {
                            "$ref": "#/definitions/models.BFFDeleteServiceResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input payload",
                        "schema": {
                            "$ref": "#/definitions/models.BFFDeleteServiceResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized role",
                        "schema": {
                            "$ref": "#/definitions/models.BFFDeleteServiceResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BFFDeleteServiceResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BFFAddMechanicRequest": {
            "type": "object",
            "properties": {
                "aadhar_number": {
                    "type": "string",
                    "example": "112233445566"
                },
                "name": {
                    "type": "string",
                    "example": "Mukesh roy"
                },
                "phone": {
                    "type": "integer",
                    "example": 9881463919
                }
            }
        },
        "models.BFFAddMechanicResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "Successfully added"
                }
            }
        },
        "models.BFFAddNewServiceRequest": {
            "type": "object",
            "required": [
                "service"
            ],
            "properties": {
                "amount": {
                    "type": "number",
                    "minimum": 99,
                    "example": 1745.99
                },
                "service": {
                    "type": "string",
                    "minLength": 3,
                    "example": "painting"
                }
            }
        },
        "models.BFFAddNewServiceResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "service added successfully"
                }
            }
        },
        "models.BFFDeleteMechanicRequest": {
            "type": "object",
            "properties": {
                "aadhar_number": {
                    "type": "string",
                    "example": "112233445566"
                }
            }
        },
        "models.BFFDeleteMechanicResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "Successfully deleted"
                }
            }
        },
        "models.BFFDeleteServiceRequest": {
            "type": "object",
            "required": [
                "service"
            ],
            "properties": {
                "service": {
                    "type": "string",
                    "minLength": 3,
                    "example": "painting"
                }
            }
        },
        "models.BFFDeleteServiceResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "service deleted successfully"
                }
            }
        },
        "models.ErrorAPIResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "errors": {
                    "$ref": "#/definitions/models.ErrorMessage"
                }
            }
        },
        "models.ErrorMessage": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
