// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/vehicles/add-mechanic": {
            "post": {
                "description": "Handles mechanic add request by validating input and storing mechanics details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mechanics"
                ],
                "summary": "Adds new mechanic",
                "parameters": [
                    {
                        "description": "mechanic add Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BFFAddMechanicRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "mechanic added successfully",
                        "schema": {
                            "$ref": "#/definitions/models.BFFAddMechanicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input payload",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "409": {
                        "description": "Duplicate value in request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    }
                }
            }
        },
        "/api/vehicles/delete-mechanic": {
            "post": {
                "description": "Handles mechanic Delete request by validating input.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Mechanics"
                ],
                "summary": "Delete mechanic",
                "parameters": [
                    {
                        "description": "mechanic Delete Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BFFDeleteMechanicRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "mechanic Deleted successfully",
                        "schema": {
                            "$ref": "#/definitions/models.BFFDeleteMechanicResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input payload",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BFFAddMechanicRequest": {
            "type": "object",
            "properties": {
                "aadhar_number": {
                    "type": "string",
                    "example": "112233445566"
                },
                "name": {
                    "type": "string",
                    "example": "Mukesh roy"
                },
                "phone": {
                    "type": "string",
                    "example": "9881463919"
                }
            }
        },
        "models.BFFAddMechanicResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "Successfully added"
                }
            }
        },
        "models.BFFDeleteMechanicRequest": {
            "type": "object",
            "properties": {
                "aadhar_number": {
                    "type": "string",
                    "example": "112233445566"
                }
            }
        },
        "models.BFFDeleteMechanicResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "Successfully deleted"
                }
            }
        },
        "models.ErrorAPIResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "errors": {
                    "$ref": "#/definitions/models.ErrorMessage"
                }
            }
        },
        "models.ErrorMessage": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
