definitions:
  models.BFFAddMechanicRequest:
    properties:
      aadhar_number:
        example: "112233445566"
        type: string
      name:
        example: Mukesh roy
        type: string
      phone:
        example: "9881463919"
        type: string
    type: object
  models.BFFAddMechanicResponse:
    properties:
      status:
        example: Successfully added
        type: string
    type: object
  models.BFFDeleteMechanicRequest:
    properties:
      aadhar_number:
        example: "112233445566"
        type: string
    type: object
  models.BFFDeleteMechanicResponse:
    properties:
      status:
        example: Successfully deleted
        type: string
    type: object
  models.ErrorAPIResponse:
    properties:
      error:
        type: string
      errors:
        $ref: '#/definitions/models.ErrorMessage'
    type: object
  models.ErrorMessage:
    properties:
      errorMessage:
        type: string
      key:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/vehicles/add-mechanic:
    post:
      consumes:
      - application/json
      description: Handles mechanic add request by validating input and storing mechanics
        details
      parameters:
      - description: mechanic add Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BFFAddMechanicRequest'
      produces:
      - application/json
      responses:
        "201":
          description: mechanic added successfully
          schema:
            $ref: '#/definitions/models.BFFAddMechanicResponse'
        "400":
          description: Invalid input payload
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
        "409":
          description: Duplicate value in request
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
        "500":
          description: Internal Server error
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
      summary: Adds new mechanic
      tags:
      - Mechanics
  /api/vehicles/delete-mechanic:
    post:
      consumes:
      - application/json
      description: Handles mechanic Delete request by validating input.
      parameters:
      - description: mechanic Delete Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BFFDeleteMechanicRequest'
      produces:
      - application/json
      responses:
        "200":
          description: mechanic Deleted successfully
          schema:
            $ref: '#/definitions/models.BFFDeleteMechanicResponse'
        "400":
          description: Invalid input payload
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
        "500":
          description: Internal Server error
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
      summary: Delete mechanic
      tags:
      - Mechanics
swagger: "2.0"
