definitions:
  models.BFFAddMechanicRequest:
    properties:
      aadhar_number:
        example: "112233445566"
        type: string
      name:
        example: Mukesh Roy
        type: string
      phoneNumber:
        example: 8432805566
        maximum: 9999999999
        minimum: 1000000000
        type: integer
    required:
    - aadhar_number
    - name
    - phoneNumber
        example: Mukesh roy
        type: string
      phone:
        example: 9881463919
        type: integer
    type: object
  models.BFFAddMechanicResponse:
    properties:
      status:
        example: Successfully added
        type: string
    type: object
  models.BFFAddNewServiceRequest:
    properties:
      amount:
        example: 1745.99
        minimum: 99
        type: number
      service:
        example: painting
        minLength: 3
        type: string
    required:
    - service
    type: object
  models.BFFAddNewServiceResponse:
    properties:
      message:
        example: service added successfully
        type: string
    type: object
  models.BFFDeleteMechanicRequest:
    properties:
      aadhar_number:
        example: "112233445566"
        type: string
    type: object
  models.BFFDeleteMechanicResponse:
    properties:
      status:
        example: Successfully deleted
        type: string
    type: object
  models.BFFDeleteServiceRequest:
    properties:
      service:
        example: painting
        minLength: 3
        type: string
    required:
    - service
    type: object
  models.BFFDeleteServiceResponse:
    properties:
      message:
        example: service deleted successfully
        type: string
    type: object
  models.ErrorAPIResponse:
    properties:
      error:
        type: string
      errors:
        $ref: '#/definitions/models.ErrorMessage'
    type: object
  models.ErrorMessage:
    properties:
      errorMessage:
        type: string
      key:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/mechanics/add:
    post:
      consumes:
      - application/json
      description: Handles mechanic add request by validating input and storing mechanics
        details
      parameters:
      - description: mechanic add Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BFFAddMechanicRequest'
      produces:
      - application/json
      responses:
        "201":
          description: mechanic added successfully
          schema:
            $ref: '#/definitions/models.BFFAddMechanicResponse'
        "400":
          description: Invalid input payload
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
        "409":
          description: Duplicate value in request
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
        "500":
          description: Internal Server error
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
      summary: Adds new mechanic
      tags:
      - Mechanics
  /api/mechanics/delete:
    post:
      consumes:
      - application/json
      description: Handles mechanic Delete request by validating input.
      parameters:
      - description: mechanic Delete Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BFFDeleteMechanicRequest'
      produces:
      - application/json
      responses:
        "200":
          description: mechanic Deleted successfully
          schema:
            $ref: '#/definitions/models.BFFDeleteMechanicResponse'
        "400":
          description: Invalid input payload
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
        "500":
          description: Internal Server error
          schema:
            $ref: '#/definitions/models.ErrorAPIResponse'
      summary: Delete mechanic
      tags:
      - Mechanics
  /api/services/add:
    post:
      consumes:
      - application/json
      description: Adds a new service to the DB
      parameters:
      - description: Add Service Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BFFAddNewServiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Added service successful
          schema:
            $ref: '#/definitions/models.BFFAddNewServiceResponse'
        "400":
          description: Invalid input payload
          schema:
            $ref: '#/definitions/models.BFFAddNewServiceResponse'
        "401":
          description: Unauthorized role
          schema:
            $ref: '#/definitions/models.BFFAddNewServiceResponse'
        "409":
          description: Service already exists
          schema:
            $ref: '#/definitions/models.BFFAddNewServiceResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BFFAddNewServiceResponse'
      security:
      - BearerAuth: []
      summary: Add a new service
      tags:
      - Services
  /api/services/delete:
    delete:
      consumes:
      - application/json
      description: Deletes an existing service from the DB
      parameters:
      - description: Delete Service Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.BFFDeleteServiceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Deleted service successful
          schema:
            $ref: '#/definitions/models.BFFDeleteServiceResponse'
        "400":
          description: Invalid input payload
          schema:
            $ref: '#/definitions/models.BFFDeleteServiceResponse'
        "401":
          description: Unauthorized role
          schema:
            $ref: '#/definitions/models.BFFDeleteServiceResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BFFDeleteServiceResponse'
      summary: Delete an existing service
      tags:
      - Services
swagger: "2.0"
