// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Authenticates user and returns JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Login registered user or admin",
                "parameters": [
                    {
                        "description": "User Sign In Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BFFLoginUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/models.BFFLoginUserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input payload",
                        "schema": {
                            "$ref": "#/definitions/models.BFFLoginUserResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/models.BFFLoginUserResponse"
                        }
                    },
                    "404": {
                        "description": "User does not exist",
                        "schema": {
                            "$ref": "#/definitions/models.BFFLoginUserResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.BFFLoginUserResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Handles customer registration by validating input and storing user details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create a new customer",
                "parameters": [
                    {
                        "description": "Customer Registration Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BFFCreateCustomerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Customer created successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid input payload",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorAPIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BFFCreateCustomerRequest": {
            "type": "object",
            "required": [
                "confirmPassword",
                "customerName",
                "email",
                "password",
                "phoneNumber"
            ],
            "properties": {
                "confirmPassword": {
                    "type": "string",
                    "minLength": 8,
                    "example": "Admin@123"
                },
                "customerName": {
                    "type": "string",
                    "maxLength": 32,
                    "minLength": 5,
                    "example": "Arjit"
                },
                "email": {
                    "type": "string",
                    "example": "arijit@gmail.com"
                },
                "password": {
                    "type": "string",
                    "maxLength": 20,
                    "minLength": 8,
                    "example": "Admin@123"
                },
                "phoneNumber": {
                    "type": "integer",
                    "maximum": 9999999999,
                    "minimum": 1000000000,
                    "example": 7568912340
                }
            }
        },
        "models.BFFLoginUserRequest": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "example": "Admin@123"
                },
                "role": {
                    "type": "string",
                    "example": "customer or admin"
                }
            }
        },
        "models.BFFLoginUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "user loggedin successfully"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "models.ErrorAPIResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "errors": {
                    "$ref": "#/definitions/models.ErrorMessage"
                }
            }
        },
        "models.ErrorMessage": {
            "type": "object",
            "properties": {
                "errorMessage": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "x-extension-openapi": "{\"example\": \"value on a json format\"}"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Authentication Service API",
	Description:      "Authentication APIs for Garage Management System",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
